const bikes=[
{id:"r1",name:"MOTOX R1",type:"Supersport",price:1850000,engine:"998cc",power:"210 HP",speed:"299 KM/H",torque:"113 Nm",weight:"195 KG",image:"https://commons.wikimedia.org/wiki/Special:FilePath/2015_Yamaha_YZF-R1.JPG?width=700"},
{id:"street-x",name:"MOTOX STREET X",type:"Street",price:875000,engine:"765cc",power:"95 HP",speed:"210 KM/H",torque:"78 Nm",weight:"187 KG",image:"https://commons.wikimedia.org/wiki/Special:FilePath/Yamaha_MT-07.jpg?width=700"},
{id:"cruiser",name:"MOTOX CRUISER",type:"Cruiser",price:1240000,engine:"1200cc",power:"105 HP",speed:"190 KM/H",torque:"110 Nm",weight:"256 KG",image:"https://commons.wikimedia.org/wiki/Special:FilePath/Harley_Davidson_(1).jpg?width=700"},
{id:"adventure",name:"MOTOX ADVENTURE",type:"Adventure",price:1520000,engine:"890cc",power:"115 HP",speed:"220 KM/H",torque:"92 Nm",weight:"215 KG",image:"https://commons.wikimedia.org/wiki/Special:FilePath/BMW_R1200GS_Adventure.JPG?width=700"},
{id:"naked-z",name:"MOTOX NAKED Z",type:"Street",price:960000,engine:"799cc",power:"108 HP",speed:"225 KM/H",torque:"86 Nm",weight:"185 KG",image:"https://commons.wikimedia.org/wiki/Special:FilePath/2021_Black_Yamaha_MT-07.jpg?width=700"},
{id:"rr310",name:"MOTOX RR 310",type:"Supersport",price:325000,engine:"312cc",power:"34 HP",speed:"160 KM/H",torque:"27 Nm",weight:"174 KG",image:"https://commons.wikimedia.org/wiki/Special:FilePath/2014_Yamaha_YZF-R1.JPG?width=700"}
];
const accessories=[
["MOTOX Helmet","Helmet",4100,"https://commons.wikimedia.org/wiki/Special:FilePath/AraiHelmet.JPG?width=900"],
["Riding Jacket","Jacket",12000,"https://commons.wikimedia.org/wiki/Special:FilePath/MotoEqipments%20HelmetBootsJacketAndGloves.jpg?width=900"],
["Racing Gloves","Gloves",4500,"https://commons.wikimedia.org/wiki/Special:FilePath/Dainese%20racing%20gloves.jpg?width=900"],
["Performance Exhaust","Exhaust",18000,"https://static.summitracing.com/global/images/prod/xlarge/ysh-11170e0520_xl.jpg"],
["Touring Bag","Bag",6500,"https://www.moto24.de/media/catalog/product/cache/b2033513abe27381d3788f77964ba8df/u/t/ut806.jpg"],
["Bike Cover","Cover",2200,"https://webstore.procycleonline.com/cdn/shop/products/131077_1080x.jpg?v=1587658354"]
];
const money=n=>"₹"+n.toLocaleString("en-IN");
function renderShell(){document.getElementById("header").innerHTML=`<header class="navbar"><a class="logo" href="index.html">MOTO<span>X</span></a><nav class="nav-links"><a href="index.html">Home</a><a href="motorcycles.html">Motorcycles</a><a href="compare.html">Compare</a><a href="customize.html">Customize</a><a href="service.html">Service</a><a href="accessories.html">Accessories</a><a href="gallery.html">Gallery</a><a href="dealers.html">Dealers</a></nav><div class="nav-actions"><button class="nav-icon" onclick="openSearch()">⌕</button><a class="nav-icon" href="wishlist.html">♡</a><a class="nav-icon" href="cart.html">🛒</a><button class="login-button" onclick="logout()">Logout</button></div><button class="mobile-menu" onclick="toggleMenu()">☰</button></header><div id="searchOverlay" class="search-overlay"><div class="search-box"><button class="close" onclick="closeSearch()">×</button><h2>Search Motorcycles</h2><input id="searchInput" placeholder="Search..."><button class="btn" onclick="performSearch()">Search</button></div></div>`;document.getElementById("footer").innerHTML=`<footer class="footer"><div class="footer-content footer-bike-info"><div class="footer-brand"><a class="logo" href="index.html">MOTO<span>X</span></a><p>Premium motorcycles. Extraordinary experiences.</p><p class="footer-note">Explore performance motorcycles built around power, control, technology and everyday riding confidence.</p></div><div class="footer-bike-column"><h4>Motorcycle Details</h4><p><b>Supersport</b> — Track-focused performance and high-speed engineering.</p><p><b>Street</b> — Agile handling for everyday road riding.</p><p><b>Cruiser</b> — Strong torque, relaxed ergonomics and long-distance comfort.</p></div><div class="footer-bike-column"><h4>Performance Range</h4><p>312cc–1200cc engines</p><p>34–210 HP power range</p><p>160–299 KM/H top-speed range</p></div><div class="footer-bike-column"><h4>MOTOX Promise</h4><p>Premium design</p><p>Advanced rider technology</p><p>Confident braking and handling</p></div></div><div class="footer-bottom"><span>© 2026 MOTOX. All Rights Reserved.</span><span>Premium Motorcycle Showroom</span></div></footer>`}
function bikeCard(b){return `<article class="card"><div class="card-image"><img src="${b.image}" alt="${b.name}" loading="lazy" onerror="this.onerror=null;this.src='https://loremflickr.com/640/480/motorcycle?lock=${b.id.length}'"></div><div class="card-body"><p>${b.type}</p><h3>${b.name}</h3><span class="price">${money(b.price)}</span><div class="card-actions"><a class="small-btn" href="bike-details.html?id=${b.id}">Explore</a><button class="small-btn" onclick="addToCart('${b.id}')">Add to cart</button><button class="small-btn wishlist-btn" onclick="openBikeFromWishlist('${b.id}')" title="Save to wishlist and view bike details">♡ Wishlist</button></div></div></article>`}
function addToCart(id){let c=JSON.parse(localStorage.getItem("motoxCart")||"[]");if(!c.includes(id))c.push(id);localStorage.setItem("motoxCart",JSON.stringify(c));toast("Added to cart")}
function addToWishlist(id){let w=JSON.parse(localStorage.getItem("motoxWishlist")||"[]");if(!w.includes(id))w.push(id);localStorage.setItem("motoxWishlist",JSON.stringify(w));toast("Saved to wishlist")}
function openBikeFromWishlist(id){addToWishlist(id);setTimeout(()=>{location.href="bike-details.html?id="+encodeURIComponent(id)},180)}
function toast(t){const x=document.createElement("div");x.className="toast";x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),1800)}
function openSearch(){document.getElementById("searchOverlay").style.display="grid";document.getElementById("searchInput").focus()}
function closeSearch(){document.getElementById("searchOverlay").style.display="none"}
function performSearch(){const q=document.getElementById("searchInput").value.trim();if(q)location.href="motorcycles.html?search="+encodeURIComponent(q)}
function toggleMenu(){document.querySelector(".nav-links").classList.toggle("show")}
document.addEventListener("DOMContentLoaded",()=>{if(document.getElementById("header"))renderShell();const f=document.getElementById("featured");if(f)f.innerHTML=bikes.slice(0,3).map(bikeCard).join("");const hb=document.getElementById("heroBikeImg");if(hb)hb.src=bikes[0].image.replace("width=700","width=1000")});

function logout(){localStorage.removeItem("motoxLoggedIn");location.replace("login.html");}
